100 lighting
Minywire/Bottlebrush_Engine pull request #112
Opened 2024-05-14 09:08 UTC by Minywire

## What problem does this pull request address?

Our singular environment light was acting as a point light, when we wanted a directional light to act as a sun to light up our scene.

It is part of issue #100 

## How does this pull request solve the problem?

This PR solves the problem by modifying the shader to take a light direction instead of a light position, and modifying the diffuse calculations so that it no longer requires a position. 

## What testing has been performed?

I built it, and I ran it, and here's a pretty picture so you know I'm not just lying ❤️ 
![image](https://github.com/Minywire/Bottlebrush_Engine/assets/51070144/78342ecb-7559-4230-a100-dbb70a7c2502)

- [x] Builds successfully
- [x] Runs successfully

2024-05-14 09:25 UTC, Idraliski requested changes
Just a couple of changes requested

2024-05-14 09:25 UTC, Idraliski commented on Bottlebrush_Engine/Bottlebrush_Engine/Resources/Shaders/Fragment/BasicTex.frag
> +
Should this be here if we are not using it?

2024-05-14 09:25 UTC, Idraliski commented on Bottlebrush_Engine/Bottlebrush_Engine/BBComponentSystem/Systems.cpp
> +    renderEngine.GetShader(shaderType)->SetUniform3f("direction", -0.2f, -1.0f, -0.3f);
I believe the sun is in the other direction with respect to the fake lighting from the skybox.

2024-05-14 09:26 UTC, Minywire commented on Bottlebrush_Engine/Bottlebrush_Engine/BBComponentSystem/Systems.cpp
> +    renderEngine.GetShader(shaderType)->SetUniform3f("direction", -0.2f, -1.0f, -0.3f);
Fair enough, I can change this

2024-05-14 09:53 UTC, Minywire commented on Bottlebrush_Engine/Bottlebrush_Engine/Resources/Shaders/Fragment/BasicTex.frag
> +
we are iirc

2024-05-14 09:54 UTC, Minywire commented on Bottlebrush_Engine/Bottlebrush_Engine/Resources/Shaders/Fragment/BasicTex.frag
> +
OH WAIT - thats there for when i refactor to take materials instead of hardcoded texture files

2024-05-14 09:56 UTC, Idraliski commented on Bottlebrush_Engine/Bottlebrush_Engine/Resources/Shaders/Fragment/BasicTex.frag
> +
ah okay, thats fine with me then

2024-05-14 10:16 UTC, Idraliski requested changes
Changes are being made, as discussed on Discord

2024-05-14 11:23 UTC, jdilanzo approved these changes

2024-05-15 03:40 UTC, Idraliski approved these changes
Refactor to happen in next PR

2024-05-15 05:19 UTC, The-Spaghetti-Is-Ready approved these changes
Haha my eyes are burning

2024-05-21 15:50 UTC, merged