89 ai init
Minywire/Bottlebrush_Engine pull request #114
Opened 2024-05-15 07:13 UTC by Idraliski

## What problem does this pull request address?
We need a start point of the AI engine, and start implementing the Singleton Pattern.

## How does this pull request solve the problem?
This creates a few needed classes for the AI engine, The FSM (state machine), State, and Singleton.

Creates a Finite State Machine class to be used as a component for entities, although it is not specifically implemented as one yet. It is made to handle any subclass of State, which is currently using C++ implementation for now, but easy to re-write once we find a suitable method to pass objects to Lua and back.

Creates an Abstract State class which will be the interface for making concrete State classes in the future, it handles transitions to and from states in an easy manner with onEnter(), Update(), and onExit() methods. Should take on any object types as it is templated.

Creates a templated Singleton class to ensure only one instance of an object is made. States has been made Singletons.

closes #113, and addresses issue #89

## What testing has been performed?
No Tests are being performed

- [x] Builds successfully
- [x] Runs successfully

2024-05-21 02:32 UTC, The-Spaghetti-Is-Ready commented on Bottlebrush_Engine/Bottlebrush_Engine/BBAI/NPC.h
does the FSM for this class need to be a pointer?

2024-05-21 04:00 UTC, Idraliski commented on Bottlebrush_Engine/Bottlebrush_Engine/BBAI/NPC.h
this is incomplete, its as a pointer currently as I am attempting to use the Singleton class for FSM

2024-05-21 15:25 UTC, Idraliski commented on Bottlebrush_Engine/Bottlebrush_Engine/BBAI/NPC.h
changed it now, its just a member var now

2024-05-21 15:50 UTC, Minywire submitted a review, later dismissed
This looks really good!

2024-05-21 17:22 UTC, The-Spaghetti-Is-Ready requested changes
As per Andrew's recommendations, changes are needed to this branch

2024-05-22 05:06 UTC, Idraliski commented
Addressed issues brought up, please re-review

2024-05-22 09:00 UTC, The-Spaghetti-Is-Ready approved these changes
Looks good, I can't see any issues with this.  Thanks for adding delta time to scene as well, I completely forgot about that

2024-05-22 15:14 UTC, Minywire approved these changes
after looking at the conversation in discord and here i'm happy to approve this

2024-05-22 15:28 UTC, merged