120 adding terrain into scene
Minywire/Bottlebrush_Engine pull request #121
Opened 2024-05-29 16:05 UTC by The-Spaghetti-Is-Ready

## What problem does this pull request address?

This is a stepping stone toward solving issues #120 , #99 . This change enables for the scripting of terrain into the game. It also allows for instantiation of the terrain so more than one terrain mesh can be rendered in the scene by storing. 

The old terrain instance in entrypoint is still there, but only because the camera is currently still dependant on it. This will be addressed in the next fix. This is currently just enabling terrain to be in the scene. 

## How does this pull request solve the problem?

This problem is addressed by allowing for terrain serializable scripts to be created, which can then be loaded into a scene script with the `create_entity` function in the master script, specifying the the location of the terrain. This terrain is then loaded into the ECS and managed by the engine resource manager. 

One concern with this is 'detecting' the collision in the terrain. Since the current terrain collision is dependant on a terrain instance's dimensions in relation to the camera, fetching parameters for all terrain instances to calculate collision may prove to be expensive. This would be addressed by setting up actual dynamic collision bodies (either with React or other implementations) and then applying them to the terrain, instead having the camera fetch terrain data directly.

Currently the player doesn't follow or 'collide' with the terrain because the camera has not been moved to scene yet, as mentioned in the section above.

An issue encountered by implementation was the shader settings not matching the old implementation, so the saturation of the color of the terrain is slightly different in this new implementation. This doesn't necessarily need to be addressed as the shader logic is still the same, the colors just need to be adjusted. Will need to talk to @jdilanzo to figure out the original color settings.

Screenshot of ECS-instantiated terrain:

![BOTTLE BRUSH 30_05_24 00_02_42](https://github.com/Minywire/Bottlebrush_Engine/assets/77040582/4edae145-2b3f-45ed-a01d-8ca29a4bc1f6)

## What testing has been performed?

 
- [x] Builds successfully
- [x] Runs successfully
- [x] Scripts are loaded properly 
- [x] Terrain renders as expected

2024-05-29 16:11 UTC, The-Spaghetti-Is-Ready commented on Bottlebrush_Engine/Bottlebrush_Engine/BBComponentSystem/Systems.cpp
> +        sceneTerrain.emplace(std::pair<std::string, Terrain>(terrainComp.terrain_path, Terrain(terrainComp.terrain_path, terrainComp.terrain_texture, glm::vec3(1.0f,1.0f,1.0f), terrainComp.terrain_sh
setting a hardcoded glm::vec3 scale here as the scale of the terrain will be updated anyways with the model matrix during render-time. It's better this way so that the terrain mesh can be referenced multiple times without having to mess with the internal scale data.

2024-05-30 00:48 UTC, Minywire commented
Just clarifying for now, we're only moving forward with heightmap terrain for the submission?

2024-05-30 01:05 UTC, jdilanzo commented on Bottlebrush_Engine/Bottlebrush_Engine/BBComponentSystem/Systems.cpp
> +        sceneTerrain.emplace(std::pair<std::string, Terrain>(terrainComp.terrain_path, Terrain(terrainComp.terrain_path, terrainComp.terrain_texture, glm::vec3(1.0f,1.0f,1.0f), terrainComp.terrain_sh
@The-Spaghetti-Is-Ready you can omit the scale and shift entirely when constructing a terrain because they have default values in the ctor.

2024-05-30 01:06 UTC, jdilanzo commented
> Just clarifying for now, we're only moving forward with heightmap terrain for the submission?

@Minywire probably best to keep it to a heightmap for submission to make NPC + object placement easier. I can provide facilities in the terrain class for fractal generation either way, so it's something we can mention.

2024-05-30 01:08 UTC, jdilanzo commented
@The-Spaghetti-Is-Ready the colour values should be based on the texture pixel colours. If the terrain shader has changed then that might make things look different.

2024-05-30 05:59 UTC, jdilanzo submitted a review, later dismissed

2024-05-30 11:24 UTC, Idraliski requested changes
Other than the one thing i commented on. Everything else looks fine to me

2024-05-30 11:24 UTC, Idraliski commented on Bottlebrush_Engine/Bottlebrush_Engine/BBComponentSystem/Systems.cpp
> +        transform = glm::rotate(transform, currentTransformComponent.rotation.z, glm::vec3(0,0,1));
I think we just comment this out, as it would affect our current `getHeight` method if it was rotated. same reasoning as why the translate and scale is commented out. Up until we cater for the transform specs within terrain's `getHeight`

2024-05-30 11:40 UTC, Idraliski approved these changes
LGTM NOW

2024-05-30 12:10 UTC, jdilanzo approved these changes

2024-05-30 12:13 UTC, merged